project:
  type: website
  render:
    - "*.qmd"
    - "!data/**"

website:
  title: "hxyap"
  navbar:
    left:
      - text: "exercises"
        menu: 
          - text: "ex1"
            href: "exercises/ex1/ex1.html"
          - text: "ex2"
            href: "exercises/ex2/ex2.html"
      - text: "In-class Exercises"
        menu:
          - text: "ex1"
            href: "In-class_Ex/ICE-1/ice1.html"
          - text: "ex2"
            href: "In-class_Ex/ICE-2/ice2.html"
          - text: "ex3"
            href: "In-class_Ex/ICE-3/ice3.html"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

